baseURL = 'https://icodeit.com.au/'
languageCode = 'en-us'
title = 'I Code It'
theme = "paper"

[params]
  # color style
  color = 'gray'                 # linen, wheat, gray, light
  disableHLJS = true

  # header social icons
  twitter = 'JuntaoQiu'     # twitter.com/YOUR_TWITTER_ID
  github = 'abruzzi'       # github.com/YOUR_GITHUB_ID

  # home page profile
  name = 'Juntao Qiu'
  bio = 'Hey, my name is Juntao. I am a developer, a YouTuber and an author. I help people write better code.'
  

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4  