baseURL = 'https://icodeit.com.au/'
languageCode = 'en-us'
title = 'I Code It'
theme = "icodeit"

[params]
  disableHLJS = true

  # header social icons
  twitter = 'JuntaoQiu'
  github = 'abruzzi'
  rss = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4  
