baseURL = 'https://icodeit.com.au'
languageCode = 'en-us'
title = 'I Code It'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Books'
pageRef = '/books'
weight = 20

[[menus.main]]
name = 'Courses'
pageRef = '/courses'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
